### ISSUE TITLE
flask_wtf nicht gefunden

### ISSUE THREAD

**Issue by FSTW-THL** [FSTW-THL/MyKlaus2#2]
im Modul forms.py  wirft die Zeile "from flask_wtf import FlaskForm" ein Error das flask_wtf nicht gefunden wurde

**Comment by AltPlusF4** [comment]
Du musst das Module noch installieren damit er es findet

**Comment by AltPlusF4** [comment]
Lösungsweg in Visual Studio

Nachdem du das Projekt geöffnet hast musst du im Projektmanager unter deinen Python-Umgebungen eine Rechtsklick machen, bei mir ist es "Python 3.6 (64-bit)" [https://ibb.co/vst20f6](Siehe Bild).
Und dann wählst du im Dropdown Menu "Aus 'requirements.txt' installieren" aus [https://ibb.co/BwtCggt](Siehe Bild).

Alternativ kannst du auch im CMD folgenden Befehl eingeben:
`pip install -r requirements.txt`
Allerding solltest du dafür entweder zum Projektverzeichnis navigiert haben oder den vollständigen Pfad für die "requirements.txt" angeben.
